### ISSUE TITLE
Help needed, want to autostart lirc2mqtt.

### ISSUE THREAD

**Issue by masterxilef** [hobbyquaker/lirc2mqtt#2]
Hello,
I'm working on a home automation system with a raspberry pi as a hub for a relay and an ir transmitter using lirc, planning to control it all with openhab running on my server.
After searching quite a bit for a way to interact with lirc via openhab or mqtt I found your code and tried it.
It works great, I'm still testing my code and hardware but so far so good, I can send mqtt commands to send IR signals and control my devices. Thank you.
The only thing I'm not able to do it's start lirc2mqtt at boot, I was planning on using rc.local just because I don't need anything more, I'm already using it to subscribe to a mqtt topic for other devices. Do you have any advice?
Thanks again for your work.

**Comment by hobbyquaker** [comment]
Hi,
I'm using [PM2](https://github.com/Unitech/pm2) for handling my node processes, but there are many more way to to do this. Take a look here: http://stackoverflow.com/questions/4018154/node-js-as-a-background-service
Regards,
Sebastian

**Comment by masterxilef** [comment]
Thanks, that was usefull. I will try the windows option.
In linux I eventually succeded with adding it to rc.local, I had a bad line before the one for lirc2mqtt so lirc2mqtt wasn't executing.
Thanks.
